### ISSUE TITLE
[ES] Install Multi Node Docker Compose

### ISSUE THREAD

**Issue by SeokRae** [devOops-org/devOps#6]
멀티 노드를 클러스터로 실행할 수 있는 Docker Compose 설정 및 테스트

**Comment by SeokRae** [comment]
멀티노드를 설정한  docker compose 실행 중 하나의 노드가 계속 다운됨

`
es03    | {"type": "server", "timestamp": "2020-12-20T07:02:02,214Z", "level": "WARN", "component": "o.e.d.SeedHostsResolver", "cluster.name": "es-docker-cluster", "node.name": "es03", "message": "failed to resolve host [es01]",
es03    | "stacktrace": ["java.net.UnknownHostException: es01: Name or service not known",
es03    | "at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]",
es03    | "at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]",
es03    | "at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]",
es03    | "at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]",
es03    | "at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]",
es03    | "at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]",
es03    | "at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]",
es03    | "at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:556) ~[elasticsearch-7.10.1.jar:7.10.1]",
es03    | "at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:498) ~[elasticsearch-7.10.1.jar:7.10.1]",
es03    | "at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:864) ~[elasticsearch-7.10.1.jar:7.10.1]",
es03    | "at org.elasticsearch.discovery.SeedHostsResolver.lambda$resolveHostsLists$0(SeedHostsResolver.java:144) ~[elasticsearch-7.10.1.jar:7.10.1]",
es03    | "at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]",
es03    | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) ~[elasticsearch-7.10.1.jar:7.10.1]",
es03    | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
es03    | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
es03    | "at java.lang.Thread.run(Thread.java:832) [?:?]"] }
`

**Comment by SeokRae** [comment]
> 멀티노드를 설정한 docker compose 실행 중 하나의 노드가 계속 다운됨
> 
> `es03 | {"type": "server", "timestamp": "2020-12-20T07:02:02,214Z", "level": "WARN", "component": "o.e.d.SeedHostsResolver", "cluster.name": "es-docker-cluster", "node.name": "es03", "message": "failed to resolve host [es01]", es03 | "stacktrace": ["java.net.UnknownHostException: es01: Name or service not known", es03 | "at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]", es03 | "at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]", es03 | "at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]", es03 | "at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]", es03 | "at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]", es03 | "at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]", es03 | "at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]", es03 | "at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:556) ~[elasticsearch-7.10.1.jar:7.10.1]", es03 | "at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:498) ~[elasticsearch-7.10.1.jar:7.10.1]", es03 | "at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:864) ~[elasticsearch-7.10.1.jar:7.10.1]", es03 | "at org.elasticsearch.discovery.SeedHostsResolver.lambda$resolveHostsLists$0(SeedHostsResolver.java:144) ~[elasticsearch-7.10.1.jar:7.10.1]", es03 | "at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]", es03 | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) ~[elasticsearch-7.10.1.jar:7.10.1]", es03 | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]", es03 | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]", es03 | "at java.lang.Thread.run(Thread.java:832) [?:?]"] }`

노트북에 설정되어 있는 Docker의 메모리가 부족하여 컨테이너가 뜨지 않는 문제
각 컨테이너의 heap size가 512로 설정하여 최소 1.5g를 필요로 함

docker 기존 heap size가 2g로 설정되어 있어 위 컨테이너가 실행될 수 있도록 메모리를 늘려 정상 수행되도록 수정
